import{a as b,S as v,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function u(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const S="51729967-cf115d8e1e17df6f8ee5ef85d",q="https://pixabay.com/api/",R=15;async function f(r,t){try{return(await b.get(q,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:R}})).data}catch(o){throw console.error("Error fetching images:",o),o}}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(o=>`
      <li class="photo-card">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()}function B(){p.innerHTML=""}function y(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function w(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const P=document.querySelector(".form"),$=document.querySelector(".load-more");let i="",s=1,d=0;P.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements["search-text"].value.trim(),!i){a.warning({title:"Warning",message:"Enter a query to search for images",position:"topRight",timeout:3e3});return}B(),l(),s=1,y();try{const t=await f(i,s);if(d=t.totalHits,t.hits.length===0){a.warning({message:"Sorry, no images found. Try another keyword.",position:"topRight"});return}g(t.hits),d>t.hits.length&&w()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});$.addEventListener("click",async()=>{s+=1,l(),y();try{const r=await f(i,s);g(r.hits),s*15>=d?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(),M()}catch{a.error({message:"Failed to load more images.",position:"topRight"})}finally{L()}});function M(){const{height:r}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
